// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoTQ6odr8JoyH4fRpYUq20AiFvo2DkJGw',
    appId: '1:573415984674:web:7660cc2fe798dada7d847b',
    messagingSenderId: '573415984674',
    projectId: 'test-crud-2dd44',
    authDomain: 'test-crud-2dd44.firebaseapp.com',
    storageBucket: 'test-crud-2dd44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZlqtL1GLNVXC35YuBwPb-xtZX5ZKO4aY',
    appId: '1:573415984674:android:92bc61647f5835a87d847b',
    messagingSenderId: '573415984674',
    projectId: 'test-crud-2dd44',
    storageBucket: 'test-crud-2dd44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX8JHoC1bC8D_MQAYdPEUvl1DhlOc7ttI',
    appId: '1:573415984674:ios:72ce63e1acd250ca7d847b',
    messagingSenderId: '573415984674',
    projectId: 'test-crud-2dd44',
    storageBucket: 'test-crud-2dd44.appspot.com',
    iosClientId: '573415984674-n42e58ln3q98bptith6hsf6ngtha04qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapa01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX8JHoC1bC8D_MQAYdPEUvl1DhlOc7ttI',
    appId: '1:573415984674:ios:72ce63e1acd250ca7d847b',
    messagingSenderId: '573415984674',
    projectId: 'test-crud-2dd44',
    storageBucket: 'test-crud-2dd44.appspot.com',
    iosClientId: '573415984674-n42e58ln3q98bptith6hsf6ngtha04qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapa01',
  );
}
